### PR TITLE
modify script to access nci tools

### PR DESCRIPTION
**Pull request by supernord**
Changes to:

gadi function
2_tools section that uses gadi function
attributions

### CODE REVIEW

**Comment by ghost** [comment]
The NCI part looks good to me. It might be worth keeping a cached copy of the apps list at `../../external_GitHub_inputs/gadi.csv` if the `GET` fails for whatever reason. The service has proven more robust now that its behind a load balancer, but I have had to take it offline for updates a couple of times. I would hate to inadvertently break the biocommons tool listing as a result. Perhaps adding a `tryCatch` block to check for the case of a connection refused error (i.e. service down) and a check that the HTTP status code from the `GET` is 200 before attempting to parse the list. If either of those tests fails, parse the cached list instead. Eventually, retrieval of the cached list can be automated, as we discussed over email last week.

**Comment by supernord** [comment]
Thanks for the suggestions @dsr900. I've added a `tryCatch` block and the status code check. The script now also writes to `../../external_GitHub_inputs` to create `gadi.csv`, and also retrieves this file if the `GET` fails.

Would you mind having another look before I merge this branch?

**Comment by ghost** [comment]
Hi Johan. I don't think your `tryCatch` block will read from `../../external_GitHub_inputs/gadi.csv` if the `GET` fails, only when the return code is not 200. I think `error=function(error)` needs to contain `gadi_tibble_temp <- read_csv("../../external_GitHub_inputs/gadi.csv", col_names = c("toolID", "version"))`. If you'd like to test the effect of the server being down, change the port number to 5001, and you'll get a connection refused error. An attempt to `GET` any path other than `/dump` will give a status code of 401 if you'd like to test that error condition as well.

Furthermore, there is a race condition on writing the csv. Unless you're certain that all requests to the tools listing are serialized on the backend, it is entirely possible for two (or more) simultaneous requests to start writing to `../../external_GitHub_inputs/gadi.csv` at the same time. Resolving this requires an atomic rewrite/replacement operation on the file. The usual way to do this is to write to a uniquely named temporary file, then issue a `rename` operation on that file over the existing file. I'd suggest implementing an age limit on the file as well, so it doesn't get rewritten on every request to the tools listing, which will improve performance. Something like:
if `../../external_GitHub_inputs/gadi.csv` does not exist or if `../../external_GitHub_inputs/gadi.csv` is older than `ageLimit` seconds:
generate unique tempfile name, e.g. with `uuid` or similar
`write_csv(gadi_tibble_temp, <unique tempfile name>)`
`file.rename(<unique tempfile name>,../../external_GitHub_inputs/gadi.csv)`
If the backend filesystem is posix-compliant, and if the R implementation of `rename` is correct, then this will be an atomic operation, and will guard against multiple simultaneous writes to `gadi.csv`. Unfortunately, it doesn't completely eliminate the possibility of a race condition, as there is a chance of a name collision in the temporary file, but using something like `uuid` for name generation makes this very unlikely and not worth worrying about.

Of course, none of this guards against the case where `../../external_GitHub_inputs/gadi.csv` does not exist and the apps service is down on the first request to the tools listing. I think the only solution in that case is to put the file in place manually once, before these changes go live.

Apologies for continually adding complexity to this project. You've inadvertently implemented a cache for the apps service, and deciding when and how to update a cache (cache invalidation) is one of the more difficult problems in computer science. I'm sure that once you start the major update, you'll encounter problems like this one (e.g. What happens when a request comes in while the tool list creation code is running? What happens when one of the tool list updates fails? etc.), so whatever you come up with here will be relevant to that, it won't be wasted effort.

**Comment by ghost** [comment]
Looks good now, Johan. I'm not an R programmer, so can't comment on code correctness, but the atomic cache update and error handling functionality looks to be all there.

**Review by ghost — APPROVED** [review]
Looks good, as per comments on the PR page.

**Pull request merged**
